version: "3.8"
services:
  proxy:
    image: caddy:2.7
    container_name: uiw_proxy
    restart: unless-stopped
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - gateway
      - openwebui
      - ollama
      - vocechat
      - tts
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [uiw_net]

  web:
    build: ./web
    container_name: uiw_web
    restart: unless-stopped
    env_file: .env
    depends_on: [gateway]
    expose: ["3000"]
    networks: [uiw_net]

  gateway:
    build: ./gateway
    container_name: uiw_gateway
    restart: unless-stopped
    env_file: .env
    depends_on: [db, minio, redis]
    expose: ["4000"]
    networks: [uiw_net]

  db:
    image: postgres:16-alpine
    container_name: uiw_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose: ["5432"]
    networks: [uiw_net]

  redis:
    image: redis:7-alpine
    container_name: uiw_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    expose: ["6379"]
    networks: [uiw_net]

  minio:
    image: minio/minio:latest
    container_name: uiw_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    expose:
      - "9000"
      - "9001"
    networks: [uiw_net]

  ollama:
    image: ollama/ollama:latest
    container_name: uiw_ollama
    tty: true
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    expose: ["11434"]
    networks: [uiw_net]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: uiw_openwebui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on: [ollama]
    volumes:
      - openwebui_data:/app/backend/data
    expose: ["8080"]
    networks: [uiw_net]

  tts:
    image: rhasspy/wyoming-piper:latest
    container_name: uiw_tts
    # Starts both Wyoming (10200) and HTTP server (5000). Voice can be changed later.
    command: ["--voice", "en_US-lessac-medium", "--download-dir", "/data", "--data-dir", "/data"]
    volumes:
      - tts_data:/data
    expose:
      - "5000"
      - "10200"
    networks: [uiw_net]

  vocechat:
    image: privoce/vocechat-server:latest
    container_name: uiw_vocechat
    restart: unless-stopped
    environment:
      - PORT=3000
    volumes:
      - vocechat_data:/data
    expose: ["3000"]
    networks: [uiw_net]

networks:
  uiw_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  db_data:
  redis_data:
  minio_data:
  ollama_data:
  openwebui_data:
  tts_data:
  vocechat_data:
